---
title: Initial Questions
author: Hayden Steinmann
execute:
 code-fold: true
---

# Stage 2.1: Initial Explorations of the Dataset.

## About
These first four questions look at school demographics and incident/disciplinary reports.

### Dataset
The dataset is [NC DPI School Report Card Resources for Researchers](https://www.dpi.nc.gov/data-reports/school-report-cards/school-report-card-resources-researchers).  It is stored in the `datasets_files` folder. Since the file was so large I only included the files that I was planning to use, however the entire zipfile can be downloaded at the link above. In the `datasets_files` folder I also included the data dictionary that's labeled `SRC_Data_Dictionary_202425.xlsx`

### Research Question
I initially posed three research questions all of which are pretty broad and go in slightly different directions. I'm hoping by the end of Stage 2 I'll be able to narrow it down and have a better understanding of that data that's infront of me. The questions included: 1. How the geographic patterns of school/neighborhood segregation in Mecklenburg County may shape patterns of juvenile and young adult criminal legal system involvement, how  residential segregation shapes the geography of police encounters in Mecklenburg County, and how the geographic distribution of racial and socioeconomic school segregation in Mecklenburg County has changed over time. I defintely can't answer all of these in my project but am confident that the data and information for at least one of them exists.

## Loading and Merging Initial Datasets

```{python}
import pandas as pd
from pyprojroot import here

file_path = here("projects/hayden_project/datasets_files/rcd_inc2.xlsx")
inc_dis = pd.read_excel(file_path)

print(inc_dis.shape)
print(inc_dis.head())
print(inc_dis.columns.tolist())
```

```{python}
print(inc_dis['year'].value_counts().sort_index())
print(inc_dis['subgroup'].value_counts())
print(inc_dis['agency_code'].nunique())
```

```{python}
location = pd.read_excel(here("projects/hayden_project/datasets_files/rcd_location.xlsx"))

print(location.shape)
print(location.head())
print(location.columns.tolist())
```

I have to merge two different data sets so that I can properly look at both incident/disciplinary reports and racial disparity information. This was kind of a lot of work and I hate merging so I hope I did it right. Stack Overflow came in clutch. I did a lot of print statemetns so that I could see what I was looking at and what was included in each dataset.

This is merging the two datasets I'm going to be looking at and is also filtering them so that it's only schools in Mecklenburg County and the year 2025

```{python}
inc_dis_2025 = inc_dis[inc_dis['year'] == 2025].copy()

location_2025 = location[location['year'] == 2025].copy()

merge_2025 = inc_dis_2025.merge(
 location_2025,
 on = ['year', 'agency_code'],
 how = 'left')

meck_2025 = merge_2025[
 (merge_2025['county'] == 'Mecklenburg') & (merge_2025['agency_level'] == 'SCH')]

print(meck_2025.shape)
print(meck_2025['name'].nunique())
```

## Question 1: What kinds of disciplinary incidents are reported in Mecklenburg schools?

OKKK!!! I can finally ask my first question. I want to get a general understanding of the types of reports that happen in schools and which ones are most common. The dataset includes several different types of incidents including, in-school suspension, expulsion, criminal acts, bullying, etc. I went ahead and filtered the data so that each school only appears once instead of including multiple student subgroups. This left me with 221 schools.

```{python}
# Looking only at all students rather than individual subgroups
meck_all = meck_2025[meck_2025['subgroup'] == 'ALL'].copy()

print(meck_all.shape)
print(meck_all['name'].nunique())
```

I then looked at the median rate of each type of incident per 1000 students.

```{python}
print("Median rate per 1,000 students:")

print("In-school suspension:", meck_all['iss_per1000'].median())
print("Short-term suspension:", meck_all['sts_per1000'].median())
print("Long-term suspension:", meck_all['lts_per1000'].median())
print("Expulsion:", meck_all['exp_per1000'].median())
print("Criminal acts:", meck_all['act_per1000'].median())
print("Bullying/harassment:", meck_all['bha_per1000'].median())
print("Law enforcement referrals:", meck_all['rpt_per1000'].median())
print("School-related arrests:", meck_all['arr_per1000'].median())
```

Right off the bat we see that short-term suspension and in-school suspension have the highest median rates at 34.63 and 43.87, respectively. When comparing these to the number of law enforcement referrals and school-related arrests the numbers vary quite drastically. I think this was a good first exploration as it makes me wonder whether certain groups of students experience these forms of discipline at higher rates and especially whether the 1.84 median rate of law enforcements referrals consists of a certain demographic.

## Question 2: How do short-term and in-school suspension rates differ across racial groups?

Ok next up I'm going to be filtering the data so that it looks at some of the student subgroups that I mentioned above.

```{python}
race = meck_2025[meck_2025['subgroup'].isin(['BL7', 'WH7', 'HI7', 'AS7', 'MU7'])].copy()

print(race[['subgroup', 'sts_per1000', 'iss_per1000']].groupby('subgroup').median())
```

WOW. This highlights a pretty staggering difference. These values are based on median values and show that the short-term suspension rate for Black students was nearly five times the rate of white students, at 85.44 and 17.54 respectively. Hispanic and Multiracial (MU) also had higher rates than white students, not quite as drastic but still a noticeable difference. While this pattern was quite clear, I'm interested if there's any other factors that may contribute to these suspension rates.

## Quesiton 3: Is a pattern present surrounding economic status?

```{python}
economic = meck_2025[meck_2025['subgroup'].isin(['EDS', 'NEDS'])].copy()

print(economic[['subgroup', 'sts_per1000', 'iss_per1000']].groupby('subgroup').median())
```

Another pretty clear trend. Economically disadvantaged students had in-school and short-term suspension rates over double those of non-economically disadvantaged students. Since a pattern exists when comparing suspension rates to both race and economic status, I'm curious whether a pattern exists between these two variables and how they vary by individaul school.

## Question 4: Do schools with different racial/socioeconomic breakdowns have different disciplinary rates?

For this I unfortunately needed a new data file from the same dataset so I'm going to load that in quickly.

```{python}
eds = pd.read_excel(here("projects/hayden_project/datasets_files/rcd_acc_eds.xlsx"))

print(eds.shape)
print(eds.head())
print(eds.columns.tolist())
```

Ok more merging needs to happen. It's pretty repetitive to above.

```{python}
eds_2025 = eds[eds['year'] == 2025].copy()

meck_eds = meck_all.merge(
 eds_2025,
 on = ['year', 'agency_code'],
 how = 'left')
```

Another unfortunate event is that within this dataset I couldn't seem to find a file that gave the racial demographic breakdown of each school so that's something that I'm going to have to keep searching for. In the meantime we can look at this datafile that gives us the percentage of students at each school that are economically disadvantaged (EDS). While I'm expecting the answer to be that a high EDS population will correlate to a high STS and ISS rates lets confirm.

```{python}
print("Lowest % EDS", meck_eds['pct_eds'].min())

print("Highest % EDS", meck_eds['pct_eds'].max())

print("Median % EDS", meck_eds['pct_eds'].median())
```

```{python}
print(meck_eds[['name', 'pct_eds', 'sts_per1000', 'iss_per1000']].sort_values('pct_eds').head(10))

print(meck_eds[['name', 'pct_eds', 'sts_per1000', 'iss_per1000']].sort_values('pct_eds', ascending = False).head(10))
```

This is quite interesting to look at. I think it brings up an important statistical point as I need to make sure that as I move forward I'm looking at the size of each individaul school. Schools that have an STS/ISS rate of 500+ may be relatively small schools making their numbers relatively skewed so this is an important to look closer at. A relatively small school could have super high numbers, but this ultimately is reflective of fewer students. Looking at the 10 schools with the lowest percent of EDS we see that their STS and ISS rates are relatively low when compared to the 10 schools with the highest percent of EDS. It's confirming to see this in actual numebrs as it shows that the questions we looked at above were leading us in the right direction.