{
  "hash": "599781be5ce7e70e2e616cd286c55273",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: Initial Questions\nauthor: Hayden Steinmann\nexecute:\n code-fold: true\n---\n\n# Stage 2.1: Initial Explorations of the Dataset.\n\n## About\nThese first four questions look at school demographics and incident/disciplinary reports.\n\n### Dataset\nThe dataset is [NC DPI School Report Card Resources for Researchers](https://www.dpi.nc.gov/data-reports/school-report-cards/school-report-card-resources-researchers).  It is stored in the `datasets_files` folder. Since the file was so large I only included the files that I was planning to use, however the entire zipfile can be downloaded at the link above. In the `datasets_files` folder I also included the data dictionary that's labeled `SRC_Data_Dictionary_202425.xlsx`\n\n### Research Question\nI initially posed three research questions all of which are pretty broad and go in slightly different directions. I'm hoping by the end of Stage 2 I'll be able to narrow it down and have a better understanding of that data that's infront of me. The questions included: 1. How the geographic patterns of school/neighborhood segregation in Mecklenburg County may shape patterns of juvenile and young adult criminal legal system involvement, how  residential segregation shapes the geography of police encounters in Mecklenburg County, and how the geographic distribution of racial and socioeconomic school segregation in Mecklenburg County has changed over time. I defintely can't answer all of these in my project but am confident that the data and information for at least one of them exists.\n\n## Loading and Merging Initial Datasets\n\n::: {#c911a951 .cell execution_count=1}\n``` {.python .cell-code}\nimport pandas as pd\nfrom pyprojroot import here\n\nfile_path = here(\"projects/hayden_project/datasets_files/rcd_inc2.xlsx\")\ninc_dis = pd.read_excel(file_path)\n\nprint(inc_dis.shape)\nprint(inc_dis.head())\nprint(inc_dis.columns.tolist())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n(283181, 19)\n   year agency_code subgroup  iss_per1000  iss_mask_code  sts_per1000  \\\n0  2018      00A000      ALL        0.000              0        0.000   \n1  2018      00A000      EDS        0.000              0        0.000   \n2  2018      00A000      ELS        0.000              0        0.000   \n3  2018      00A000      SWD        0.000              0        0.000   \n4  2018      00B000      ALL        0.506              0        0.506   \n\n   sts_mask_code  lts_per1000  lts_mask_code  exp_per1000  exp_mask_code  \\\n0              0          0.0              0          0.0              0   \n1              0          0.0              0          0.0              0   \n2              0          0.0              0          0.0              0   \n3              0          0.0              0          0.0              0   \n4              0          0.0              0          0.0              0   \n\n   act_per1000  act_mask_code  bha_per1000  bha_mask_code  rpt_per1000  \\\n0          0.0              0        0.000              0          0.0   \n1          0.0              0        0.000              0          0.0   \n2          0.0              0        0.000              0          0.0   \n3          0.0              0        0.000              0          0.0   \n4          0.0              0        0.506              0          0.0   \n\n   rpt_mask_code  arr_per1000  arr_mask_code  \n0              0          0.0              0  \n1              0          0.0              0  \n2              0          0.0              0  \n3              0          0.0              0  \n4              0          0.0              0  \n['year', 'agency_code', 'subgroup', 'iss_per1000', 'iss_mask_code', 'sts_per1000', 'sts_mask_code', 'lts_per1000', 'lts_mask_code', 'exp_per1000', 'exp_mask_code', 'act_per1000', 'act_mask_code', 'bha_per1000', 'bha_mask_code', 'rpt_per1000', 'rpt_mask_code', 'arr_per1000', 'arr_mask_code']\n```\n:::\n:::\n\n\n::: {#66d50576 .cell execution_count=2}\n``` {.python .cell-code}\nprint(inc_dis['year'].value_counts().sort_index())\nprint(inc_dis['subgroup'].value_counts())\nprint(inc_dis['agency_code'].nunique())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nyear\n2018    27674\n2019    26444\n2020    24243\n2021    36344\n2022    33132\n2023    45144\n2024    45184\n2025    45016\nName: count, dtype: int64\nsubgroup\nALL     22192\nEDS     22147\nMALE    22037\nSWD     21923\nFEM     21725\nWH7     21715\nBL7     21314\nHI7     21058\nMU7     20546\nELS     18644\nAS7     16311\nAM7     15090\nPI7     13099\nNEDS     8460\nNELS     8460\nNSWD     8460\nName: count, dtype: int64\n3133\n```\n:::\n:::\n\n\n::: {#c857b902 .cell execution_count=3}\n``` {.python .cell-code}\nlocation = pd.read_excel(here(\"projects/hayden_project/datasets_files/rcd_location.xlsx\"))\n\nprint(location.shape)\nprint(location.head())\nprint(location.columns.tolist())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n(54113, 24)\n   year agency_code agency_level designation_Type  \\\n0  2006      010303          SCH                P   \n1  2006      010304          SCH                P   \n2  2006      010308          SCH                P   \n3  2006      010310          SCH                P   \n4  2006      010320          SCH                P   \n\n                                       name category_code lea_code    county  \\\n0  Alamance-Burlington Middle/Early College             H   010LEA  Alamance   \n1               Alexander Wilson Elementary             E   010LEA  Alamance   \n2                    Altamahaw Ossipee Elem             E   010LEA  Alamance   \n3                          Broadview Middle             M   010LEA  Alamance   \n4                      E M Yoder Elementary             E   010LEA  Alamance   \n\n             street_addr street_addr2  ... grade_span     school_type  \\\n0  1247 Jimmie Kerr Road          NaN  ...      09:12  Regular School   \n1             2518 NC 54          NaN  ...      PK:05  Regular School   \n2           2832 N NC 87          NaN  ...      KG:05  Regular School   \n3   2229 Broadview Drive          NaN  ...      06:08  Regular School   \n4   301 N Charles Street          NaN  ...      PK:05  Regular School   \n\n          calendar_type                         url super_name title_i  \\\n0  Traditional Calendar   http://amc.abss.k12.nc.us        NaN     NaN   \n1  Traditional Calendar   http://awe.abss.k12.nc.us        NaN     NaN   \n2  Traditional Calendar   http://aoe.abss.k12.nc.us        NaN     NaN   \n3  Traditional Calendar  http://brm.abss.k12.nc.us/        NaN     NaN   \n4  Traditional Calendar   http://eye.abss.k12.nc.us        NaN     NaN   \n\n  residing_district esea stem purple_star  \n0               NaN  NaN  NaN         NaN  \n1               NaN  NaN  NaN         NaN  \n2               NaN  NaN  NaN         NaN  \n3               NaN  NaN  NaN         NaN  \n4               NaN  NaN  NaN         NaN  \n\n[5 rows x 24 columns]\n['year', 'agency_code', 'agency_level', 'designation_Type', 'name', 'category_code', 'lea_code', 'county', 'street_addr', 'street_addr2', 'city', 'state', 'zip', 'phone', 'grade_span', 'school_type', 'calendar_type', 'url', 'super_name', 'title_i', 'residing_district', 'esea', 'stem', 'purple_star']\n```\n:::\n:::\n\n\nI have to merge two different data sets so that I can properly look at both incident/disciplinary reports and racial disparity information. This was kind of a lot of work and I hate merging so I hope I did it right. Stack Overflow came in clutch. I did a lot of print statemetns so that I could see what I was looking at and what was included in each dataset.\n\nThis is merging the two datasets I'm going to be looking at and is also filtering them so that it's only schools in Mecklenburg County and the year 2025\n\n::: {#aea35326 .cell execution_count=4}\n``` {.python .cell-code}\ninc_dis_2025 = inc_dis[inc_dis['year'] == 2025].copy()\n\nlocation_2025 = location[location['year'] == 2025].copy()\n\nmerge_2025 = inc_dis_2025.merge(\n location_2025,\n on = ['year', 'agency_code'],\n how = 'left')\n\nmeck_2025 = merge_2025[\n (merge_2025['county'] == 'Mecklenburg') & (merge_2025['agency_level'] == 'SCH')]\n\nprint(meck_2025.shape)\nprint(meck_2025['name'].nunique())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n(3527, 41)\n221\n```\n:::\n:::\n\n\n## Question 1: What kinds of disciplinary incidents are reported in Mecklenburg schools?\n\nOKKK!!! I can finally ask my first question. I want to get a general understanding of the types of reports that happen in schools and which ones are most common. The dataset includes several different types of incidents including, in-school suspension, expulsion, criminal acts, bullying, etc. I went ahead and filtered the data so that each school only appears once instead of including multiple student subgroups. This left me with 221 schools.\n\n::: {#a8a7a6a0 .cell execution_count=5}\n``` {.python .cell-code}\n# Looking only at all students rather than individual subgroups\nmeck_all = meck_2025[meck_2025['subgroup'] == 'ALL'].copy()\n\nprint(meck_all.shape)\nprint(meck_all['name'].nunique())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n(221, 41)\n221\n```\n:::\n:::\n\n\nI then looked at the median rate of each type of incident per 1000 students.\n\n::: {#dba43619 .cell execution_count=6}\n``` {.python .cell-code}\nprint(\"Median rate per 1,000 students:\")\n\nprint(\"In-school suspension:\", meck_all['iss_per1000'].median())\nprint(\"Short-term suspension:\", meck_all['sts_per1000'].median())\nprint(\"Long-term suspension:\", meck_all['lts_per1000'].median())\nprint(\"Expulsion:\", meck_all['exp_per1000'].median())\nprint(\"Criminal acts:\", meck_all['act_per1000'].median())\nprint(\"Bullying/harassment:\", meck_all['bha_per1000'].median())\nprint(\"Law enforcement referrals:\", meck_all['rpt_per1000'].median())\nprint(\"School-related arrests:\", meck_all['arr_per1000'].median())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nMedian rate per 1,000 students:\nIn-school suspension: 34.6257\nShort-term suspension: 43.8671\nLong-term suspension: 0.0\nExpulsion: 0.0\nCriminal acts: 1.5760999999999998\nBullying/harassment: 11.6573\nLaw enforcement referrals: 1.83745\nSchool-related arrests: 0.0\n```\n:::\n:::\n\n\nRight off the bat we see that short-term suspension and in-school suspension have the highest median rates at 34.63 and 43.87, respectively. When comparing these to the number of law enforcement referrals and school-related arrests the numbers vary quite drastically. I think this was a good first exploration as it makes me wonder whether certain groups of students experience these forms of discipline at higher rates and especially whether the 1.84 median rate of law enforcements referrals consists of a certain demographic.\n\n## Question 2: How do short-term and in-school suspension rates differ across racial groups?\n\nOk next up I'm going to be filtering the data so that it looks at some of the student subgroups that I mentioned above.\n\n::: {#91913cad .cell execution_count=7}\n``` {.python .cell-code}\nrace = meck_2025[meck_2025['subgroup'].isin(['BL7', 'WH7', 'HI7', 'AS7', 'MU7'])].copy()\n\nprint(race[['subgroup', 'sts_per1000', 'iss_per1000']].groupby('subgroup').median())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n          sts_per1000  iss_per1000\nsubgroup                          \nAS7            0.0000      0.00000\nBL7           85.4434     69.82395\nHI7           19.6078     20.08030\nMU7           38.4615     27.02700\nWH7           17.5439     11.36360\n```\n:::\n:::\n\n\nWOW. This highlights a pretty staggering difference. These values are based on median values and show that the short-term suspension rate for Black students was nearly five times the rate of white students, at 85.44 and 17.54 respectively. Hispanic and Multiracial (MU) also had higher rates than white students, not quite as drastic but still a noticeable difference. While this pattern was quite clear, I'm interested if there's any other factors that may contribute to these suspension rates.\n\n## Quesiton 3: Is a pattern present surrounding economic status?\n\n::: {#4222c78d .cell execution_count=8}\n``` {.python .cell-code}\neconomic = meck_2025[meck_2025['subgroup'].isin(['EDS', 'NEDS'])].copy()\n\nprint(economic[['subgroup', 'sts_per1000', 'iss_per1000']].groupby('subgroup').median())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n          sts_per1000  iss_per1000\nsubgroup                          \nEDS          59.58080     49.99265\nNEDS         24.08595     18.07430\n```\n:::\n:::\n\n\nAnother pretty clear trend. Economically disadvantaged students had in-school and short-term suspension rates over double those of non-economically disadvantaged students. Since a pattern exists when comparing suspension rates to both race and economic status, I'm curious whether a pattern exists between these two variables and how they vary by individaul school.\n\n## Question 4: Do schools with different racial/socioeconomic breakdowns have different disciplinary rates?\n\nFor this I unfortunately needed a new data file from the same dataset so I'm going to load that in quickly.\n\n::: {#0dc6f2e9 .cell execution_count=9}\n``` {.python .cell-code}\neds = pd.read_excel(here(\"projects/hayden_project/datasets_files/rcd_acc_eds.xlsx\"))\n\nprint(eds.shape)\nprint(eds.head())\nprint(eds.columns.tolist())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n(25222, 4)\n   year agency_code  pct_eds  pct_eds_masking\n0  2017      00A000     44.8              NaN\n1  2017      00B000     66.2              NaN\n2  2017      010303     43.8              NaN\n3  2017      010304     48.3              NaN\n4  2017      010308     48.0              NaN\n['year', 'agency_code', 'pct_eds', 'pct_eds_masking']\n```\n:::\n:::\n\n\nOk more merging needs to happen. It's pretty repetitive to above.\n\n::: {#9824808e .cell execution_count=10}\n``` {.python .cell-code}\neds_2025 = eds[eds['year'] == 2025].copy()\n\nmeck_eds = meck_all.merge(\n eds_2025,\n on = ['year', 'agency_code'],\n how = 'left')\n```\n:::\n\n\nAnother unfortunate event is that within this dataset I couldn't seem to find a file that gave the racial demographic breakdown of each school so that's something that I'm going to have to keep searching for. In the meantime we can look at this datafile that gives us the percentage of students at each school that are economically disadvantaged (EDS). While I'm expecting the answer to be that a high EDS population will correlate to a high STS and ISS rates lets confirm.\n\n::: {#8164a66c .cell execution_count=11}\n``` {.python .cell-code}\nprint(\"Lowest % EDS\", meck_eds['pct_eds'].min())\n\nprint(\"Highest % EDS\", meck_eds['pct_eds'].max())\n\nprint(\"Median % EDS\", meck_eds['pct_eds'].median())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nLowest % EDS 5.0\nHighest % EDS 85.6\nMedian % EDS 50.650000000000006\n```\n:::\n:::\n\n\n::: {#8cd1e1fa .cell execution_count=12}\n``` {.python .cell-code}\nprint(meck_eds[['name', 'pct_eds', 'sts_per1000', 'iss_per1000']].sort_values('pct_eds').head(10))\n\nprint(meck_eds[['name', 'pct_eds', 'sts_per1000', 'iss_per1000']].sort_values('pct_eds', ascending = False).head(10))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                                    name  pct_eds  sts_per1000  iss_per1000\n188  Metrolina Regional Scholars Academy      5.0       0.0000       0.0000\n133         Providence Spring Elementary      5.2       0.0000       3.3956\n187                  Lake Norman Charter      8.2      30.7553      76.8883\n215                      Telra Institute     10.7      12.8000       3.2000\n33                   Davidson Elementary     11.1      21.9780      33.8123\n4                Rea Farms STEAM Academy     13.2      34.2276      48.1036\n190         Community School of Davidson     13.8       7.3937       7.3937\n143                  Dilworth Elementary     14.8       2.4631       2.4631\n134               Providence High School     15.0      42.0561     175.7009\n2                Ardrey Kell High School     15.1      22.7273     106.3900\n                                   name  pct_eds  sts_per1000  iss_per1000\n199  Niner University Elementary School     85.6       0.0000       0.0000\n38                 Marie G Davis School     83.0     695.2381     539.6825\n168              Walter G. Byers School     82.1     376.6667     463.3333\n185                Turning Point Middle     81.9    1954.5455     136.3636\n208                    Movement Freedom     81.4       1.6667       0.0000\n120             Bruns Avenue Elementary     79.7     156.8627      14.7059\n184    Elbert Edwin Waddell High School     79.5     188.9764      15.7480\n102       Charlotte-Mecklenburg Academy     78.6    1238.0952       0.0000\n193                      KIPP Charlotte     78.4     202.0460       0.0000\n139      Renaissance West STEAM Academy     78.2     229.5989     217.1508\n```\n:::\n:::\n\n\nThis is quite interesting to look at. I think it brings up an important statistical point as I need to make sure that as I move forward I'm looking at the size of each individaul school. Schools that have an STS/ISS rate of 500+ may be relatively small schools making their numbers relatively skewed so this is an important to look closer at. A relatively small school could have super high numbers, but this ultimately is reflective of fewer students. Looking at the 10 schools with the lowest percent of EDS we see that their STS and ISS rates are relatively low when compared to the 10 schools with the highest percent of EDS. It's confirming to see this in actual numebrs as it shows that the questions we looked at above were leading us in the right direction.\n\n",
    "supporting": [
      "stage2_files"
    ],
    "filters": [],
    "includes": {}
  }
}